const START='2026-10-03',END='2026-10-09';
const STORAGE_KEY='diario_pressione_2026_10_03_09_v1',PROFILE_KEY='diario_pressione_patient_v1',EMAIL_KEY='diario_pressione_email_v1';
const $=s=>document.querySelector(s),daysList=$('#daysList'),quickForm=$('#quickForm'),patientName=$('#patientName'),recipientEmail=$('#recipientEmail');
const localISODate=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const parseLocalDate=iso=>{const[y,m,d]=iso.split('-').map(Number);return new Date(y,m-1,d,12)};
const DATES=[];for(let d=parseLocalDate(START);d<=parseLocalDate(END);d.setDate(d.getDate()+1))DATES.push(localISODate(d));
const getData=()=>{try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||{}}catch{return{}}};
const setData=d=>localStorage.setItem(STORAGE_KEY,JSON.stringify(d));
const prettyDate=(iso,weekday=false)=>new Intl.DateTimeFormat('it-IT',{weekday:weekday?'long':undefined,day:'numeric',month:'long'}).format(parseLocalDate(iso));
const slotLabel=s=>s==='morning'?'Mattina':'Sera';
function currentTarget(){const now=new Date(),today=localISODate(now);let date=today<START?START:today>END?END:today,slot=now.getHours()<15?'morning':'evening',data=getData();if(!data[date]?.morning)slot='morning';else if(!data[date]?.evening)slot='evening';return{date,slot}}
let activeTarget=currentTarget();
function validate(sys,dia,pulse){if(![sys,dia,pulse].every(Number.isFinite))return'Inserisci tutti e tre i valori.';if(sys<60||sys>260)return'Controlla il valore della massima.';if(dia<40||dia>160)return'Controlla il valore della minima.';if(pulse<30||pulse>220)return'Controlla il valore dei battiti.';if(sys<=dia)return'La massima deve essere superiore alla minima.';return''}
function saveReading(date,slot,v){const d=getData();d[date]??={};d[date][slot]={...v,savedAt:new Date().toISOString()};setData(d)}
function renderQuick(){const{date,slot}=activeTarget,r=getData()[date]?.[slot];$('#quickTitle').textContent=prettyDate(date,true);$('#quickSlot').textContent=slotLabel(slot);$('#quickSys').value=r?.sys??'';$('#quickDia').value=r?.dia??'';$('#quickPulse').value=r?.pulse??'';$('#formMessage').textContent=r?'Valori già presenti: puoi modificarli e salvare di nuovo.':'';$('#formMessage').classList.remove('error')}
function renderSummary(){const d=getData(),r=[];DATES.forEach(date=>['morning','evening'].forEach(s=>d[date]?.[s]&&r.push(d[date][s])));$('#progressValue').textContent=`${r.length}/14`;const avg=k=>r.length?Math.round(r.reduce((a,x)=>a+Number(x[k]),0)/r.length):'—';$('#avgSys').textContent=avg('sys');$('#avgDia').textContent=avg('dia');$('#avgPulse').textContent=avg('pulse')}
function renderDays(){const d=getData(),today=localISODate();daysList.innerHTML='';DATES.forEach(date=>{const n=$('#dayTemplate').content.cloneNode(true),card=n.querySelector('.day-card');if(date===today)card.classList.add('today');n.querySelector('.day-weekday').textContent=new Intl.DateTimeFormat('it-IT',{weekday:'long'}).format(parseLocalDate(date));n.querySelector('.day-date').textContent=new Intl.DateTimeFormat('it-IT',{day:'numeric',month:'long'}).format(parseLocalDate(date));const done=['morning','evening'].filter(s=>d[date]?.[s]).length,status=n.querySelector('.day-status');status.textContent=done===2?'Completo':`${done}/2`;status.classList.toggle('complete',done===2);const list=n.querySelector('.slot-list');['morning','evening'].forEach(slot=>{const r=d[date]?.[slot],row=document.createElement('div');row.className='slot-row';row.innerHTML=`<span class="slot-name">${slotLabel(slot)}</span><div class="slot-values ${r?'':'empty'}">${r?`<span><b>${r.sys}</b> max</span><span><b>${r.dia}</b> min</span><span><b>${r.pulse}</b> bpm</span>`:'<span>Nessuna registrazione</span>'}</div>`;const b=document.createElement('button');b.className='edit-btn';b.type='button';b.textContent=r?'Modifica':'Inserisci';b.onclick=()=>{activeTarget={date,slot};renderQuick();$('#quickEntry').scrollIntoView({behavior:'smooth'});setTimeout(()=>$('#quickSys').focus(),300)};row.appendChild(b);list.appendChild(row)});daysList.appendChild(n)})}
function renderAll(){renderSummary();renderDays();renderQuick()}
quickForm.addEventListener('submit',e=>{e.preventDefault();const sys=Number($('#quickSys').value),dia=Number($('#quickDia').value),pulse=Number($('#quickPulse').value),err=validate(sys,dia,pulse),m=$('#formMessage');if(err){m.textContent=err;m.classList.add('error');return}saveReading(activeTarget.date,activeTarget.slot,{sys,dia,pulse});m.textContent='Rilevazione salvata sul dispositivo.';m.classList.remove('error');if(activeTarget.date===localISODate()&&activeTarget.slot==='morning')activeTarget={date:activeTarget.date,slot:'evening'};renderSummary();renderDays();setTimeout(renderQuick,500)});
function allRows(){const d=getData(),rows=[];DATES.forEach(date=>['morning','evening'].forEach(slot=>rows.push({date,slot,...(d[date]?.[slot]||{})})));return rows}
function averages(rows){const p=rows.filter(r=>Number.isFinite(Number(r.sys)));if(!p.length)return null;const a=k=>Math.round(p.reduce((s,r)=>s+Number(r[k]),0)/p.length);return{count:p.length,sys:a('sys'),dia:a('dia'),pulse:a('pulse')}}
function textReport(){const rows=allRows(),avg=averages(rows),lines=['DIARIO DELLA PRESSIONE','Periodo: 3–9 ottobre 2026'];if(patientName.value.trim())lines.push(`Paziente: ${patientName.value.trim()}`);lines.push('','Data       Fascia    Massima  Minima  Battiti','------------------------------------------------');rows.forEach(r=>{const date=new Intl.DateTimeFormat('it-IT',{day:'2-digit',month:'2-digit',year:'numeric'}).format(parseLocalDate(r.date));lines.push(`${date}  ${slotLabel(r.slot).padEnd(9)} ${r.sys??'—'}       ${r.dia??'—'}      ${r.pulse??'—'}`)});if(avg)lines.push('',`Medie su ${avg.count} rilevazioni: massima ${avg.sys} mmHg, minima ${avg.dia} mmHg, battiti ${avg.pulse} bpm.`);return lines.join('\n')}
$('#emailBtn').onclick=()=>{location.href=`mailto:${encodeURIComponent(recipientEmail.value.trim())}?subject=${encodeURIComponent('Diario pressione 3-9 ottobre 2026')}&body=${encodeURIComponent(textReport())}`};
$('#csvBtn').onclick=()=>{const rows=allRows(),lines=['Data;Fascia;Massima_mmHg;Minima_mmHg;Battiti_bpm'];rows.forEach(r=>lines.push([r.date,slotLabel(r.slot),r.sys??'',r.dia??'',r.pulse??''].join(';')));const blob=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='diario-pressione-3-9-ottobre-2026.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),500)};
$('#printBtn').onclick=()=>print();
patientName.value=localStorage.getItem(PROFILE_KEY)||'';recipientEmail.value=localStorage.getItem(EMAIL_KEY)||'';patientName.oninput=()=>localStorage.setItem(PROFILE_KEY,patientName.value);recipientEmail.oninput=()=>localStorage.setItem(EMAIL_KEY,recipientEmail.value);
$('#resetBtn').onclick=()=>{if(confirm('Vuoi cancellare tutte le registrazioni della pressione dal dispositivo?')){localStorage.removeItem(STORAGE_KEY);activeTarget=currentTarget();renderAll()}};
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
renderAll();